In [4]:
import numpy as np;

In [5]:
arr = np.array([8,94,8,56,1,3,4,5,7])

In [6]:
arr

array([ 8, 94,  8, 56,  1,  3,  4,  5,  7])

In [7]:
index_gt10 = np.where(arr>10)

In [9]:
index_gt10 #Return index where values are satisfi

(array([1, 3]),)

In [10]:
arr[index_gt10]

array([94, 56])

In [11]:
test = arr > 10

array([False,  True, False,  True, False, False, False, False, False])

In [15]:
np.where(arr>10,'gt10','lt10')

array(['lt10', 'gt10', 'lt10', 'gt10', 'lt10', 'lt10', 'lt10', 'lt10',
       'lt10'], dtype='<U4')

In [16]:
arr

array([ 8, 94,  8, 56,  1,  3,  4,  5,  7])

In [17]:
arr.max()

94

In [18]:
arr.argmax()

1

In [19]:
arr.argmin()

4

In [21]:
arr[arr.argmin()]

1

# read and write csv file

In [26]:
data = np.genfromtxt('https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv',delimiter=',',skip_header=True, filling_values=-1000, dtype='float')

In [27]:
data.shape

(392, 9)

In [28]:
data.ndim

2

In [30]:
np.set_printoptions(suppress=True)
data[:3]

array([[   18. ,     8. ,   307. ,   130. ,  3504. ,    12. ,    70. ,
            1. , -1000. ],
       [   15. ,     8. ,   350. ,   165. ,  3693. ,    11.5,    70. ,
            1. , -1000. ],
       [   18. ,     8. ,   318. ,   150. ,  3436. ,    11. ,    70. ,
            1. , -1000. ]])

In [40]:
data2 = np.genfromtxt('https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv',delimiter=',',skip_header=1, dtype='object')
data2

array([[(18+0j), (8+0j), (307+0j), ..., (70+0j), (1+0j), None],
       [(15+0j), (8+0j), (350+0j), ..., (70+0j), (1+0j), None],
       [(18+0j), (8+0j), (318+0j), ..., (70+0j), (1+0j), None],
       ...,
       [(32+0j), (4+0j), (135+0j), ..., (82+0j), (1+0j), None],
       [(28+0j), (4+0j), (120+0j), ..., (82+0j), (1+0j), None],
       [(31+0j), (4+0j), (119+0j), ..., (82+0j), (1+0j), None]],
      dtype=object)

In [41]:
np.savetxt('data.csv',data,delimiter=',')

In [42]:
data

array([[   18.,     8.,   307., ...,    70.,     1., -1000.],
       [   15.,     8.,   350., ...,    70.,     1., -1000.],
       [   18.,     8.,   318., ...,    70.,     1., -1000.],
       ...,
       [   32.,     4.,   135., ...,    82.,     1., -1000.],
       [   28.,     4.,   120., ...,    82.,     1., -1000.],
       [   31.,     4.,   119., ...,    82.,     1., -1000.]])

In [43]:
np.save('data.npy',data)

In [44]:
np.savez('data2.npz',data, data2)

In [46]:
d = np.load('data.npy')

In [47]:
d

array([[   18.,     8.,   307., ...,    70.,     1., -1000.],
       [   15.,     8.,   350., ...,    70.,     1., -1000.],
       [   18.,     8.,   318., ...,    70.,     1., -1000.],
       ...,
       [   32.,     4.,   135., ...,    82.,     1., -1000.],
       [   28.,     4.,   120., ...,    82.,     1., -1000.],
       [   31.,     4.,   119., ...,    82.,     1., -1000.]])

In [49]:
d2 = np.load('data2.npz')

In [51]:
d2.files

['arr_0', 'arr_1']

In [52]:
d2['arr_0']

array([[   18.,     8.,   307., ...,    70.,     1., -1000.],
       [   15.,     8.,   350., ...,    70.,     1., -1000.],
       [   18.,     8.,   318., ...,    70.,     1., -1000.],
       ...,
       [   32.,     4.,   135., ...,    82.,     1., -1000.],
       [   28.,     4.,   120., ...,    82.,     1., -1000.],
       [   31.,     4.,   119., ...,    82.,     1., -1000.]])

## Concat with row and column wise

In [58]:
arr1 = np.zeros([4,4])
arr2 = np.zeros([4,4])

In [59]:
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
# np.concatenate, np.vstack, np.r_
np.concatenate([arr1,arr2],axis=0) #Row Wise
np.vstack([arr1,arr2])
np.r_[arr1,arr2]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
np.concatenate([arr1,arr2],axis=1)
np.hstack([arr1,arr2])
np.c_[arr1,arr2]

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

# Sort a numpy Array

In [69]:
arr = np.random.randint(1,10,size = [10,5])

In [70]:
arr

array([[6, 8, 1, 5, 3],
       [2, 7, 6, 6, 4],
       [8, 4, 1, 4, 1],
       [4, 6, 7, 9, 2],
       [3, 5, 9, 1, 5],
       [2, 5, 6, 9, 9],
       [9, 5, 4, 5, 8],
       [5, 2, 1, 7, 5],
       [2, 8, 6, 2, 8],
       [1, 7, 1, 7, 5]])

In [71]:
np.sort(arr)

array([[1, 3, 5, 6, 8],
       [2, 4, 6, 6, 7],
       [1, 1, 4, 4, 8],
       [2, 4, 6, 7, 9],
       [1, 3, 5, 5, 9],
       [2, 5, 6, 9, 9],
       [4, 5, 5, 8, 9],
       [1, 2, 5, 5, 7],
       [2, 2, 6, 8, 8],
       [1, 1, 5, 7, 7]])

In [72]:
np.sort(arr,axis = 0)

array([[1, 2, 1, 1, 1],
       [2, 4, 1, 2, 2],
       [2, 5, 1, 4, 3],
       [2, 5, 1, 5, 4],
       [3, 5, 4, 5, 5],
       [4, 6, 6, 6, 5],
       [5, 7, 6, 7, 5],
       [6, 7, 6, 7, 8],
       [8, 8, 7, 9, 8],
       [9, 8, 9, 9, 9]])

In [74]:
sorted_index = arr[:,0].argsort()

In [75]:
arr[sorted_index]

array([[1, 7, 1, 7, 5],
       [2, 7, 6, 6, 4],
       [2, 5, 6, 9, 9],
       [2, 8, 6, 2, 8],
       [3, 5, 9, 1, 5],
       [4, 6, 7, 9, 2],
       [5, 2, 1, 7, 5],
       [6, 8, 1, 5, 3],
       [8, 4, 1, 4, 1],
       [9, 5, 4, 5, 8]])

# working witn Dates

In [77]:
d = np.datetime64('2019-06-02')
d

numpy.datetime64('2019-06-02')

In [79]:
d = np.datetime64('2019-06-02 23:10:00')
d

numpy.datetime64('2019-06-02T23:10:00')

In [82]:
d+1000

numpy.datetime64('2019-06-02T23:26:40')

In [84]:
oneday = np.timedelta64(1,'D')

In [85]:
oneday

numpy.timedelta64(1,'D')

In [87]:
d+oneday

numpy.datetime64('2019-06-03T23:10:00')

In [88]:
oneminute = np.timedelta64(1,'m')

In [89]:
d+ oneminute

numpy.datetime64('2019-06-02T23:11:00')

In [93]:
dates = np.arange(np.datetime64('2019-06-02'),np.datetime64('2020-06-02'),2)
dates

array(['2019-06-02', '2019-06-04', '2019-06-06', '2019-06-08',
       '2019-06-10', '2019-06-12', '2019-06-14', '2019-06-16',
       '2019-06-18', '2019-06-20', '2019-06-22', '2019-06-24',
       '2019-06-26', '2019-06-28', '2019-06-30', '2019-07-02',
       '2019-07-04', '2019-07-06', '2019-07-08', '2019-07-10',
       '2019-07-12', '2019-07-14', '2019-07-16', '2019-07-18',
       '2019-07-20', '2019-07-22', '2019-07-24', '2019-07-26',
       '2019-07-28', '2019-07-30', '2019-08-01', '2019-08-03',
       '2019-08-05', '2019-08-07', '2019-08-09', '2019-08-11',
       '2019-08-13', '2019-08-15', '2019-08-17', '2019-08-19',
       '2019-08-21', '2019-08-23', '2019-08-25', '2019-08-27',
       '2019-08-29', '2019-08-31', '2019-09-02', '2019-09-04',
       '2019-09-06', '2019-09-08', '2019-09-10', '2019-09-12',
       '2019-09-14', '2019-09-16', '2019-09-18', '2019-09-20',
       '2019-09-22', '2019-09-24', '2019-09-26', '2019-09-28',
       '2019-09-30', '2019-10-02', '2019-10-04', '2019-

## Numpy Advanced Function

In [94]:
#vectorize()

In [97]:
def foo(x):
    if x%2 == 1:
        return x**2
    else:
        return x/2
    
foo(11)

121

In [101]:
foo_v = np.vectorize(foo,otypes=[float])
arr
foo_v(arr)

array([[ 3.,  4.,  1., 25.,  9.],
       [ 1., 49.,  3.,  3.,  2.],
       [ 4.,  2.,  1.,  2.,  1.],
       [ 2.,  3., 49., 81.,  1.],
       [ 9., 25., 81.,  1., 25.],
       [ 1., 25.,  3., 81., 81.],
       [81., 25.,  2., 25.,  4.],
       [25.,  1.,  1., 49., 25.],
       [ 1.,  4.,  3.,  1.,  4.],
       [ 1., 49.,  1., 49., 25.]])